'use client'

import PoliticsTitle from "../components/politics/politicsTitle/politicsTitle"
import PoliticsSubTitle from "../components/politics/politicsSubTitle/politicsSubTitle"
import PoliticsText from "../components/politics/politicsText/politicsText"
import BackBtn from "../components/backBtn/backBtn"

export default function TermsOfUse() {

    return (
        <div style={{padding: '20px', position: 'relative'}}>
            <BackBtn step={'policy'}/>
            <PoliticsTitle>Rechtsinformation</PoliticsTitle>            
            <PoliticsSubTitle>Rechtsinformation</PoliticsSubTitle>
            <PoliticsText>Die Website, die unter der Adresse www.kivismart.com/de (im Folgenden einfach „Website“) verfügbar ist, ist für den privaten Gebrauch bestimmt. Der Zugriff auf und die Nutzung dieser Website unterliegt den nachstehenden detaillierten „Regeln und Nutzungsbedingungen der Website“ sowie den geltenden Gesetzen und/oder Vorschriften eines bestimmten Landes. Indem Sie sich mit dieser Website verbinden und diese besuchen, akzeptieren Sie diese Nutzungsbedingungen vorbehaltlos und uneingeschränkt. Der Eigentümer dieser Website behält sich das Recht vor, diese Nutzungsbedingungen ohne vorherige Ankündigung zu ändern oder zu aktualisieren, und behält sich außerdem das Recht vor, Änderungen an den auf dieser Website beschriebenen Inhalten, Produkten und Dienstleistungen vorzunehmen. Jede solche Änderung ist für Benutzer obligatorisch, die die Nutzungsbedingungen dieser Website einsehen müssen.</PoliticsText>
            <PoliticsSubTitle>Rechte an geistigem Eigentum</PoliticsSubTitle>
            <PoliticsText>Der Websitebesitzer warnt Benutzer, dass ein großer Teil des Inhalts der Website:</PoliticsText>
            <PoliticsText>1. urheberrechtlich geschützt, seien es Fotos, Artikel, Projekte, Animationen und Grafiken, Audio- und Videoaufnahmen etc.;</PoliticsText>
            <PoliticsText>2. und/oder durch Gesetze geschützt sind, die die Rechte am Design der auf der Website angezeigten Automodelle schützen;</PoliticsText>
            <PoliticsText>3. marken sind durch eigene Gesetze geschützt. Insbesondere die Marken für Waren und Dienstleistungen „KIVI“, „KIVI MEDIA“. Alle diese TMs, Logos sowie alle Warenmodelle (Fernseher, Fernbedienungen, Zubehör usw.), die auf der Website angezeigt werden, sind Eigentum von KIVI oder Dritten, die von den Eigentümern der Website autorisiert wurden, diese Inhalte auf der Website zu verwenden.</PoliticsText>
            <PoliticsText>Jegliche Vervielfältigung, Präsentation, Verwendung, Anpassung, Änderung, Aufnahme, Übersetzung, ganz oder teilweise, in irgendeiner Form und mit jedem Mittel (Papier, Audio, Video, Computerbild usw.) aller oben genannten \ Logos, Marken, sowie Bilder oder andere Informationen über Produkte, die auf der Website präsentiert werden, sind verboten.</PoliticsText>
            <PoliticsText>In allen anderen Fällen wird eine solche Verwendung als Verletzung von Urheber- und/oder Designrechten und/oder Warenzeichen betrachtet und eine solche Verletzung wird gemäß den geltenden Gesetzen des jeweiligen Landes geahndet.</PoliticsText>
            <PoliticsText>Die auf der Website verwendete Software, Warenzeichen und Logos sind Eigentum der jeweiligen Unternehmen und dürfen nicht ohne Zustimmung der Eigentümer dieser Warenzeichen und Logos verwendet werden. Diese Software ist urheberrechtlich geschützt und erfordert eine Lizenzvereinbarung. Ihre Verwendung ohne die vorherige schriftliche Zustimmung des Eigentümers ist strengstens untersagt. Diese Software ist urheberrechtlich geschützt und ihre Verwendung auf der Website unterliegt einer internen Lizenzvereinbarung. Ihre unbefugte Verwendung stellt eine Verletzung des Urheberrechts dar.</PoliticsText>
            <PoliticsSubTitle>Informationen zu Produkten und Dienstleistungen</PoliticsSubTitle>
            <PoliticsText>Die auf den Seiten dieser Website präsentierten Grafiken, Fotos, Videos und Informationen basieren auf technischen Daten, die zum Zeitpunkt ihrer Platzierung auf der Website oder bei entsprechenden Ergänzungen und Änderungen an ihnen gültig waren. KIVI kann nicht garantieren, dass alle Informationen zu dem Zeitpunkt, zu dem Sie die Website aufrufen, aktuell sind. In Übereinstimmung mit der Politik der kontinuierlichen Verbesserung seiner Produkte behält sich KIVI das Recht vor, Spezifikationen, Ausstattungen, Farben und Optionen jederzeit zu ändern. Außerdem erlauben moderne Bildwiedergabetechnologien keine zuverlässige Wiedergabe von Farben. In jedem Fall werden alle Inhalte der Website rein zu Informationszwecken präsentiert und beinhalten keinerlei Verpflichtungen.</PoliticsText>
            <PoliticsText>Außerdem kann KIVI nicht garantieren, dass die Website frei von Fehlern und Viren ist, die Ihrer elektronischen Computerausrüstung und/oder Software schaden könnten. Unter Berücksichtigung der geänderten Verkaufsbedingungen gelten die Preise am Tage der Lieferung. Die angegebenen Preise gelten als empfohlen für unsere Partner. Die Preise gelten zum Zeitpunkt der Veröffentlichung, sofern nicht anders angegeben, und können ohne Vorankündigung geändert werden. Informationen zu aktuellen Preisen erhalten Sie bei den offiziellen Händlern.</PoliticsText>
            <PoliticsSubTitle>KIVI/ KIVI MEDIA und personenbezogene Daten</PoliticsSubTitle>
            <PoliticsText>Die Benutzerregistrierung auf der KIVI-Website ist kostenlos, freiwillig und erfolgt unter der Adresse im Internet: http://www.kivismart.com/de Der Benutzer der Website ist eine natürliche Person, die gemäß dem Verfahren auf der Website registriert ist der durch diese Regeln eingerichtet wurde, der das gesetzliche Mindestalter für die Annahme dieser Regeln nach den Gesetzen der Ukraine erreicht hat und über die entsprechende Befugnis verfügt (vorher und im Folgenden - der Benutzer).</PoliticsText>
            <PoliticsText>KIVI hält sich an die Bestimmungen der geltenden Gesetzgebung zum Schutz personenbezogener Daten. Alle von Ihnen bei der Nutzung dieser Website gemachten Angaben zu personenbezogenen Daten (Telefonnummern, Adressen usw.) werden von KIVI nur für die unten angegebenen Zwecke verwendet. Durch die Bereitstellung von Informationen bei der Nutzung dieser Website sowie durch jeden anderen Kontakt mit KIVI stimmen Sie zu, dass die relevanten Informationen nicht vertraulich sind und von KIVI jetzt und in Zukunft für folgende Zwecke gespeichert und verwendet werden dürfen:</PoliticsText>
            <PoliticsText>1) Bereitstellung von Informationen über Produkte, Dienstleistungen und Veranstaltungen, die für Sie von Interesse sein könnten</PoliticsText>
            <PoliticsText>2) Durchführung von Marktforschung zur Verbesserung der Qualität der Produkte und Dienstleistungen von KIVI</PoliticsText>
            <PoliticsText>3) Bereitstellung von Produkten und Dienstleistungen nach Vereinbarung mit Ihnen.</PoliticsText>
            <PoliticsText>Sie stimmen auch zu, dass KIVI diese Informationen autorisierten KIVI-Händlern sowie Unternehmen innerhalb der KIVI-Unternehmensgruppe und anderen Partnerunternehmen für die oben genannten Zwecke zur Verfügung stellt. Wenn Sie nicht möchten, dass die von Ihnen bereitgestellten Informationen an Dritte weitergegeben werden, markieren Sie bitte das entsprechende Kästchen auf jedem Formular, das Sie verwenden, um solche Informationen bereitzustellen. Insbesondere kann KIVI Ihre Telefonnummer und andere Kontaktinformationen verwenden, um Sie zu kontaktieren.</PoliticsText>
            <PoliticsText>Wenn Sie nicht möchten, dass KIVI diese Informationen verwendet, können Sie die Seite mit Ihren persönlichen Daten jederzeit löschen.</PoliticsText>
            <PoliticsSubTitle>Schutz personenbezogener Daten und Regeln für die Verwendung von Cookies</PoliticsSubTitle>
            <PoliticsText><><b>1. Personenbezogene Daten</b></></PoliticsText>
            <PoliticsText>Die Nutzung dieser Website ist ohne Angabe Ihrer personenbezogenen Daten und anderer vertraulicher Informationen möglich. In Bezug auf die personenbezogenen Daten, die Sie uns mitgeteilt haben, garantiert KIVI deren Aufbewahrung und Sicherheit. Einige personenbezogene Daten sind erforderlich, um Ihre Informationsanfragen umfassender zu erfüllen und / oder Ihre Anfrage zu bearbeiten, beispielsweise um den Newsletter zu abonnieren, und können zu diesen Zwecken an Dritte weitergegeben werden.</PoliticsText>
            <PoliticsText>Wir machen Sie darauf aufmerksam, dass zur Verbesserung der Servicequalität einige nicht personenbezogene Daten automatisch erfasst werden können, wenn Sie die Website nutzen.</PoliticsText>
            <PoliticsText><><b>2. Cookies</b></></PoliticsText>
            <PoliticsText>Der Benutzer wird darüber informiert, dass die Website Cookies verwendet. Es handelt sich um kleine Dateien, die an das Gerät des Benutzers (Computer, Laptop, Tablet, Smartphone usw.) gesendet werden, um die Navigation auf der Website zu erleichtern und Statistiken zu führen. Der Benutzer kann Cookies deaktivieren, indem er diese Option in den Browsereinstellungen auswählt.</PoliticsText>
            <PoliticsSubTitle>Haftungsausschluss und Haftung</PoliticsSubTitle>
            <PoliticsText>Durch die Nutzung dieser Website sind Sie für Ihre Handlungen voll verantwortlich. KIVI, seine Vertreter, Mitglieder des Netzwerks und andere Strukturen haften nicht für direkte oder indirekte Schäden, wie z. B. Sachschäden, Daten- oder Programmverlust, finanzielle Verluste, die sich aus der Nutzung dieser Website oder damit verbundener Websites ergeben. Wir machen Sie darauf aufmerksam, dass bestimmte Produkte oder Dienstleistungen, die auf der Website angeboten werden, in einigen Ländern besonderen Vorschriften sowie Einschränkungen unterliegen und / oder geschlossen sein können.</PoliticsText>
            <PoliticsText>Die Firma KIVI bietet Ihnen auf ihrer Website die Möglichkeit, persönliche Nachrichten über Server zu versenden, wodurch Sie anderen Personen Ihre Kontakte, Links zu Artikeln oder Dokumenten übermitteln können.</PoliticsText>
            <PoliticsSubTitle>Verantwortung des Benutzers</PoliticsSubTitle>
            <PoliticsText>Benutzer der Website verpflichten sich, diese Nutzungsbedingungen einzuhalten und nutzen die Website auf eigenes Risiko. Bei der Nutzung der Website wird automatisch davon ausgegangen, dass der Benutzer diese Nutzungsbedingungen akzeptiert hat. KIVI haftet nicht für Schäden, die durch oder im Zusammenhang mit der Nutzung dieser Website entstehen. Benutzer müssen ihre Hardware vor Viren schützen, KIVI haftet diesbezüglich nicht.</PoliticsText>
            <PoliticsSubTitle>Anwendbares Recht und Gerichtsstand</PoliticsSubTitle>
            <PoliticsText>Diese Website und die dargestellten Daten unterliegen deutschem Recht und sind in deutscher Sprache verfasst.</PoliticsText>
            <PoliticsText>Alle Streitigkeiten, die im Zusammenhang mit der Auslegung oder Umsetzung dieser Bedingungen entstehen, müssen vor den Gerichten der Ukraine gemäß der festgelegten Gerichtsbarkeit und Gerichtsbarkeit oder auf andere Weise durch gesonderte Vereinbarung mit der anderen Partei beigelegt werden.</PoliticsText>
            <PoliticsSubTitle>Rechte zur Nutzung von Fotos und Videos</PoliticsSubTitle>
            <PoliticsText>Die Rechte an Fotos und Videos, die auf der Website verwendet werden, liegen bei der Firma KIVI SMART PURCHASING, ihren Strukturen oder Partnern, sofern nicht anders angegeben. Wenn nicht anders angegeben, liegen die Rechte an Fotos und Videos bei den angegebenen Unternehmen oder bestimmten Personen.</PoliticsText>
            <PoliticsSubTitle>Gewährleistung und Haftung</PoliticsSubTitle>
            <PoliticsText>Die Informationen werden vom Unternehmen wie besehen ohne jegliche tatsächliche oder stillschweigende Gewährleistung bereitgestellt, einschließlich ohne Gewährleistung der Marktgängigkeit, der Verwendung für einen bestimmten Zweck oder der Nichtverletzung von Rechten Dritter. Auf unseren Internetseiten finden Sie auch Links zu anderen Internetangeboten. Wir weisen darauf hin, dass wir keinerlei Einfluss auf die Gestaltung und die Inhalte der gelinkten Seiten haben. Dementsprechend können wir die Aktualität, Korrektheit, Vollständigkeit oder Qualität der auf diesen Seiten bereitgestellten Daten nicht garantieren. Vor diesem Hintergrund erklären wir, dass wir uns mit den Inhalten dieser Seiten nicht zu tun haben. Diese Bestimmung gilt für alle auf unseren Internetseiten angebrachten Links zu externen Seiten und deren Inhalte.</PoliticsText>
            <PoliticsText>"KIVI". ALLE RECHTE VORBEHALTEN.</PoliticsText>
            <PoliticsText>DIE VERWENDUNG VON MATERIALIEN IST NUR MIT GENEHMIGUNG VON "LLC KIVI SMART PURCHASING".</PoliticsText>
        </div> 
    )
}